<?php

use App\Http\Controllers\HomeController;
use App\Livewire\Customer\BookingWizard;
use App\Livewire\Customer\ServicesList;
use App\Livewire\Customer\QuoteCalculator;
use Illuminate\Support\Facades\Route;
use App\Livewire\Admin\DashboardStats;
use App\Livewire\Admin\BookingManager;
use App\Livewire\Admin\MyBookings;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application.
| These routes are loaded by the RouteServiceProvider within a group
| which contains the "web" middleware group. Now create something great!
|
*/

// ============================================
// PUBLIC ROUTES (Anyone can access)
// ============================================

Route::get('/', [HomeController::class, 'index'])->name('home');

// Livewire Components (Full-page)
Route::get('/services', ServicesList::class)->name('services');
Route::get('/quote', QuoteCalculator::class)->name('quote');
Route::get('/book', BookingWizard::class)->name('book');

// ============================================
// AUTHENTICATED USER ROUTES (Logged in only)
// ============================================

Route::middleware(['auth'])->group(function () {
    Route::view('/dashboard', 'dashboard')->name('dashboard');
    Route::view('/profile', 'profile')->name('profile');
});

// ============================================
// ADMIN ROUTES (Logged in + Admin only)
// ============================================

Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', DashboardStats::class)->name('dashboard');
    Route::get('/bookings', BookingManager::class)->name('bookings');
});
 

// ============================================
// AUTHENTICATION ROUTES (Auto-generated by Breeze)
// ============================================

Route::get('/bookings', action: BookingManager::class)->name(name: 'bookings');

require __DIR__ . '/auth.php';